// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriviaAPI.Data;

#nullable disable

namespace TriviaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TriviaAPI.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "John Lennon",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "Paul McCartney",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "Bob Dylan",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "The Beatles",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "The Rolling Stones",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "The Who",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "Aretha Franklin",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "Diana Ross",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "Etta James",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "The Godfather",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "Scarface",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "Goodfellas",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "Robert De Niro",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "Al Pacino",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 15,
                            AnswerText = "Marlon Brando",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 16,
                            AnswerText = "Taxi Driver",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 17,
                            AnswerText = "Raging Bull",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 18,
                            AnswerText = "The Deer Hunter",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 19,
                            AnswerText = "1955",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 20,
                            AnswerText = "1952",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 21,
                            AnswerText = "1958",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 22,
                            AnswerText = "Dwight D. Eisenhower",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 23,
                            AnswerText = "Harry S. Truman",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 24,
                            AnswerText = "John F. Kennedy",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 25,
                            AnswerText = "Eisenhower's Farewell",
                            IsCorrect = true,
                            OrderIndex = 1,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 26,
                            AnswerText = "Churchill's Iron Curtain",
                            IsCorrect = false,
                            OrderIndex = 2,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 27,
                            AnswerText = "Truman Doctrine",
                            IsCorrect = false,
                            OrderIndex = 3,
                            QuestionId = 9
                        });
                });

            modelBuilder.Entity("TriviaAPI.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MediaType = "audio",
                            MediaUrl = "/media/imagine.mp3",
                            OrderIndex = 1,
                            QuestionText = "Who sang 'Imagine'?",
                            QuizId = 1
                        },
                        new
                        {
                            Id = 2,
                            MediaType = "image",
                            MediaUrl = "/media/beatles.jpg",
                            OrderIndex = 2,
                            QuestionText = "Which band is shown in this photo?",
                            QuizId = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderIndex = 3,
                            QuestionText = "Who sang 'Respect'?",
                            QuizId = 1
                        },
                        new
                        {
                            Id = 4,
                            MediaType = "video",
                            MediaUrl = "/media/godfather.mp4",
                            OrderIndex = 1,
                            QuestionText = "Name this classic movie scene",
                            QuizId = 2
                        },
                        new
                        {
                            Id = 5,
                            MediaType = "image",
                            MediaUrl = "/media/deniro.jpg",
                            OrderIndex = 2,
                            QuestionText = "Who is this legendary actor?",
                            QuizId = 2
                        },
                        new
                        {
                            Id = 6,
                            OrderIndex = 3,
                            QuestionText = "Complete the quote: 'You talkin' to me?'",
                            QuizId = 2
                        },
                        new
                        {
                            Id = 7,
                            MediaType = "image",
                            MediaUrl = "/media/1950s-event.jpg",
                            OrderIndex = 1,
                            QuestionText = "What year did this event occur?",
                            QuizId = 3
                        },
                        new
                        {
                            Id = 8,
                            OrderIndex = 2,
                            QuestionText = "Who was US President in 1953?",
                            QuizId = 3
                        },
                        new
                        {
                            Id = 9,
                            MediaType = "audio",
                            MediaUrl = "/media/speech.mp3",
                            OrderIndex = 3,
                            QuestionText = "Identify this famous speech",
                            QuizId = 3
                        });
                });

            modelBuilder.Entity("TriviaAPI.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "1960s Music",
                            CreatedAt = new DateTime(2026, 3, 27, 14, 45, 41, 681, DateTimeKind.Utc).AddTicks(9250),
                            IsActive = true,
                            Title = "Classic Hits from the 60s"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "1970s Movies",
                            CreatedAt = new DateTime(2026, 3, 27, 14, 45, 41, 682, DateTimeKind.Utc).AddTicks(1180),
                            IsActive = true,
                            Title = "Iconic Films of the 70s"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "1950s History",
                            CreatedAt = new DateTime(2026, 3, 27, 14, 45, 41, 682, DateTimeKind.Utc).AddTicks(1190),
                            IsActive = true,
                            Title = "Historical Events of the 50s"
                        });
                });

            modelBuilder.Entity("TriviaAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 27, 14, 45, 41, 241, DateTimeKind.Utc).AddTicks(3640),
                            Email = "admin@hotmail.com",
                            PasswordHash = "$2a$11$Zhx3M4KD/yvOjZABRkggKOnJcBON3VvNXuAy9EvOldGFKdpNRqXGS",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 27, 14, 45, 41, 540, DateTimeKind.Utc).AddTicks(5590),
                            Email = "user@hotmail.com",
                            PasswordHash = "$2a$11$/cEMC7V9yXVYOrPIGwQpwO2vH0tkVyFYgPX/llSJR5vYQyepYTiVG",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("TriviaAPI.Models.Answer", b =>
                {
                    b.HasOne("TriviaAPI.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TriviaAPI.Models.Question", b =>
                {
                    b.HasOne("TriviaAPI.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TriviaAPI.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("TriviaAPI.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
